### ISSUE TITLE
Today stop working

### ISSUE THREAD

**Issue by Sperhak-Industries** [Multarix/Discord-Hide-Blocked-Messages#9]
Script stop working for me.

**Comment by Beattman44** [comment]
same to me.

**Comment by Multarix** [comment]
I'll take a look at it when I can. It's likely discord changed something in their css.

**Comment by Multarix** [comment]
Okay guys, update is out!
Discord was overwriting our changes when we were appending to the end of the \<head\> tag, and because CSS that's further down was changing this, it now appends to the bottom of the \<body\> which isn't technically where it's supposed to be, but Discord can eat a dick ya know?

I also noticed that the timestamp is not longer being blocked (or was it not blocked to begin with? Either way, it's too much hassle to fix edge cases like this on a whim, but I can probably find a way if it annoys you guys.
![image](https://github.com/Multarix/Discord-Hide-Blocked-Messages/assets/29752805/b22a5647-5981-46ea-a1ad-4f4e537bbc21)
